import { useEffect, useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, BriefcaseBusiness, Building2, CalendarCheck2, CarFront, CheckCircle2, FileText, Link2, MessageSquareText, MoreHorizontal, Pencil, Plus, Search, ShieldCheck, Trash2, Wallet, X } from 'lucide-react';
import { useArms } from '../lib/context';
import { canReceivePayment, currency, exportCsv, formatDate, getAssignee, getCase, getCustomer, jakartaDate, type Client, type CollectionLog, type RecordData } from '../lib/data';
import { CLIENT_INDUSTRIES, COLLECTION_CHANNELS, COLLECTION_OUTCOMES, nextActionStatus } from '../lib/crm';
import { Avatar, EmptyState, Modal, Pagination, Select } from './ui';

export function ClientsModule() {
  const { db, openForm, openDetail, notify } = useArms();
  const [query, setQuery] = useState(''); const [industry, setIndustry] = useState(''); const [page, setPage] = useState(1);
  const rows = db.clients.filter(c => (!industry || c.industry === industry) && `${c.code} ${c.name} ${c.contactPerson} ${c.phone} ${c.email} ${c.regency}`.toLowerCase().includes(query.toLowerCase()));
  useEffect(() => setPage(1), [query, industry]);
  useEffect(() => setPage(p => Math.min(p, Math.max(1, Math.ceil(rows.length / 10)))), [rows.length]);
  return <div className="module-stack"><div className="crm-module-note"><Building2 size={15}/><span><strong>{db.clients.length}</strong> klien terdaftar. Satu master untuk seluruh portofolio penagihan.</span></div>
    <section className="panel"><div className="entity-toolbar"><div className="table-search"><Search size={15}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari nama, kode, atau contact person..." aria-label="Cari master klien"/>{query && <button onClick={() => setQuery('')} aria-label="Hapus pencarian"><X size={13}/></button>}</div><div className="entity-toolbar-right"><Select label="Filter industri klien" value={industry} onChange={setIndustry} options={[{ value: '', label: 'Semua industri' }, ...CLIENT_INDUSTRIES.map(value => ({ value, label: value }))]}/><button className="button button-secondary button-small" onClick={() => { exportCsv('ARMS-master-klien.csv', [['Kode Klien', 'Nama Perusahaan / Pemberi Kuasa', 'Industri', 'Contact Person', 'Telepon', 'Email', 'Kabupaten/Kota', 'Kecamatan', 'Kelurahan/Desa', 'Alamat'], ...rows.map(c => [c.code, c.name, c.industry, c.contactPerson, c.phone, c.email, c.regency, c.district, c.village, c.streetAddress])]); notify('Master klien berhasil diekspor.'); }}><ArrowDownToLine size={14}/>Ekspor</button></div></div>
      <div className="table-overflow"><table className="data-table clients-table"><thead><tr><th>Client / Creditor</th><th>Industri</th><th>Contact Person</th><th>Kontak</th><th>Domisili / Kantor</th><th>Kasus</th><th/></tr></thead><tbody>{rows.slice((page - 1) * 10, page * 10).map((c, i) => <tr key={c.id}><td><button className="name-cell" onClick={() => openDetail('clients', c)}><Avatar name={c.name} index={i}/><span><strong>{c.name}</strong><small>{c.code}</small></span></button></td><td><span className={`industry-label ${c.industry.toLowerCase()}`}>{c.industry}</span></td><td>{c.contactPerson || <span className="muted">Belum dilengkapi</span>}</td><td>{c.phone || '-'}<div className="cell-secondary">{c.email || 'Email tidak diisi'}</div></td><td>{c.regency || <span className="amber-text">Lengkapi data migrasi</span>}<div className="cell-secondary">{c.district || ''}</div></td><td><button className="number-badge" onClick={() => openDetail('clients', c)} aria-label={`Kasus ${c.name}`}>{db.cases.filter(item => item.clientId === c.id).length}</button></td><td><button className="icon-button" onClick={() => openDetail('clients', c)} aria-label={`Kelola ${c.name}`}><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div>
      {!rows.length && <EmptyState title={query || industry ? 'Klien tidak ditemukan' : 'Master klien masih kosong'} description="Daftarkan klien perusahaan atau pemberi kuasa perorangan." action={<button className="button button-primary" onClick={() => openForm('clients')}><Plus size={15}/>Register Client</button>}/>}
      <Pagination page={page} setPage={setPage} total={rows.length}/>
    </section><p className="report-note"><ShieldCheck size={15}/>Klien yang masih digunakan oleh kasus atau mutasi tidak dapat dihapus.</p>
  </div>;
}

export function CollectionsModule() {
  const { db, openForm, openDetail, notify, collectionCaseFilter, setCollectionCaseFilter } = useArms();
  const [query, setQuery] = useState(''); const [channel, setChannel] = useState(''); const [outcome, setOutcome] = useState(''); const [filter, setFilter] = useState('all'); const [page, setPage] = useState(1);
  const rows = [...db.collections].filter(log => {
    const c = getCase(db, log.caseId), customer = getCustomer(db, c?.customerId || '');
    return (!collectionCaseFilter || log.caseId === collectionCaseFilter) && (!channel || log.activity === channel) && (!outcome || log.outcome === outcome) && `${log.number} ${log.report} ${log.actionPlan} ${c?.number} ${c?.contract} ${c?.client} ${customer?.name}`.toLowerCase().includes(query.toLowerCase()) && (filter !== 'next' || (log.nextActionDate && log.nextActionDate <= jakartaDate() && c?.status !== 'Selesai')) && (filter !== 'payment' || (log.hasPayment && !db.payments.some(p => p.collectionLogId === log.id)));
  }).sort((a, b) => b.activityDate.localeCompare(a.activityDate) || b.createdAt.localeCompare(a.createdAt));
  useEffect(() => setPage(1), [query, channel, outcome, filter, collectionCaseFilter]);
  useEffect(() => setPage(p => Math.min(p, Math.max(1, Math.ceil(rows.length / 10)))), [rows.length]);
  function recordPayment(log: CollectionLog) {
    const receipt = db.payments.find(p => p.collectionLogId === log.id);
    if (receipt) { openDetail('payments', receipt); return; }
    openForm('payments', undefined, { caseId: log.caseId, collectionLogId: log.id, date: log.activityDate });
  }
  return <div className="module-stack">
    {collectionCaseFilter && <div className="active-filter-banner"><span><Link2 size={15}/>Riwayat {getCase(db, collectionCaseFilter)?.number || 'kasus'}</span><button className="text-button" onClick={() => setCollectionCaseFilter('')}>Semua kasus<X size={14}/></button></div>}
    <section className="panel"><div className="crm-log-tabs"><div className="table-tabs">{[{ id: 'all', label: 'Semua aktivitas' }, { id: 'next', label: 'Perlu tindak lanjut' }, { id: 'payment', label: 'Pembayaran belum dicatat' }].map(tab => <button key={tab.id} className={filter === tab.id ? 'active' : ''} onClick={() => setFilter(tab.id)}>{tab.label}</button>)}</div><span>{rows.length} catatan</span></div>
      <div className="entity-toolbar"><div className="table-search"><Search size={15}/><input aria-label="Cari log komunikasi" value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari berkas, debitur, atau laporan..."/></div><div className="entity-toolbar-right"><Select label="Filter kanal interaksi" value={channel} onChange={setChannel} options={[{ value: '', label: 'Semua kanal' }, ...COLLECTION_CHANNELS.map(value => ({ value, label: value }))]}/><Select label="Filter outcome" value={outcome} onChange={setOutcome} options={[{ value: '', label: 'Semua outcome' }, ...COLLECTION_OUTCOMES.map(value => ({ value, label: value }))]}/><button className="button button-small button-secondary" aria-label="Ekspor log komunikasi" onClick={() => { exportCsv('ARMS-collections-log.csv', [['No Log', 'Kasus', 'Debitur', 'Klien', 'Tanggal', 'Aktivitas', 'PIC', 'Pihak Dihubungi', 'Outcome', 'Action Plan', 'Next Action', 'Laporan', 'Ada Pembayaran', 'Kuitansi'], ...rows.map(l => { const c = getCase(db, l.caseId); return [l.number, c?.number || '', getCustomer(db, c?.customerId || '')?.name || '', c?.client || '', l.activityDate, l.activity, db.personnel.find(p => p.id === l.personnelId)?.name || '', l.contactedParty, l.outcome, l.actionPlan, l.nextActionDate, l.report, l.hasPayment ? 'Ya' : 'Tidak', db.payments.find(p => p.collectionLogId === l.id)?.number || '']; })]); notify('Log penagihan diekspor.'); }}><ArrowDownToLine size={14}/></button></div></div>
      <div className="table-overflow"><table className="data-table collections-table"><thead><tr><th>Aktivitas / Tanggal</th><th>Berkas / Debitur</th><th>Petugas / PIC</th><th>Outcome</th><th>Next Action</th><th>Pembayaran</th><th/></tr></thead><tbody>{rows.slice((page - 1) * 10, page * 10).map(log => {
        const c = getCase(db, log.caseId), receipt = db.payments.find(p => p.collectionLogId === log.id);
        return <tr key={log.id}><td><button className="case-link" onClick={() => openDetail('collections', log)}>{log.activity}</button><div className="cell-secondary">{formatDate(log.activityDate)} / {log.number}</div></td><td><button className="case-link" onClick={() => c && openDetail('cases', c)}>{c?.number}</button><div className="cell-secondary">{getCustomer(db, c?.customerId || '')?.name}</div></td><td>{db.personnel.find(p => p.id === log.personnelId)?.name || '-'}<div className="cell-secondary">{log.contactedParty}</div></td><td><div className="log-outcome">{log.outcome}</div></td><td>{log.nextActionDate ? formatDate(log.nextActionDate) : '-'}<div className={`cell-secondary ${nextActionStatus(db, log) === 'Lewat target' ? 'amber-text' : ''}`}>{nextActionStatus(db, log)}</div></td><td>{receipt ? <button className="text-button emerald-text" onClick={() => recordPayment(log)}><CheckCircle2 size={13}/>Tercatat</button> : log.hasPayment ? <div><span className="status-badge amber"><i/>Belum dicatat</span>{c && canReceivePayment(db, c) && <button className="text-button log-payment-link" onClick={() => recordPayment(log)}><Wallet size={12}/>Catat pembayaran</button>}</div> : <span className="muted">Tidak ada</span>}</td><td><button className="icon-button" aria-label={`Detail ${log.number}`} onClick={() => openDetail('collections', log)}><MoreHorizontal size={17}/></button></td></tr>;
      })}</tbody></table></div>
      {!rows.length && <EmptyState title="Belum ada catatan yang sesuai" description="Catat hasil interaksi dan tindak lanjut untuk setiap kasus." action={<button className="button button-primary" onClick={() => openForm('collections', undefined, collectionCaseFilter ? { caseId: collectionCaseFilter, personnelId: getAssignee(db, collectionCaseFilter)?.id || '' } : undefined)}><Plus size={15}/>Catat Aktivitas</button>}/>}
      <Pagination page={page} setPage={setPage} total={rows.length}/>
    </section><p className="report-note"><MessageSquareText size={15}/>Outcome dan janji bayar adalah catatan kegiatan. Saldo piutang hanya berubah setelah pembayaran disimpan.</p>
  </div>;
}

export function CrmDetail({ entity, record, onClose }: { entity: 'clients' | 'collections'; record: RecordData; onClose: () => void }) {
  const { db, openForm, openDetail, openLetter, requestDelete } = useArms();
  const current = (db[entity] as RecordData[]).find(r => r.id === record.id) || record;
  const client = entity === 'clients' ? current as Client : undefined, log = entity === 'collections' ? current as CollectionLog : undefined;
  const c = log ? getCase(db, log.caseId) : undefined, customer = getCustomer(db, c?.customerId || '');
  const receipt = log ? db.payments.find(p => p.collectionLogId === log.id) : undefined;
  const relatedCases = client ? db.cases.filter(c => c.clientId === client.id) : [];
  const details: [string, string][] = client ? [['Kode Perusahaan Klien', client.code], ['Nama Perusahaan / Pemberi Kuasa', client.name], ['Industri', client.industry], ['Contact Person', client.contactPerson || '-'], ['Phone / WhatsApp', client.phone || '-'], ['Email', client.email || '-'], ['Kabupaten/Kota', client.regency || '-'], ['Kecamatan', client.district || '-'], ['Kelurahan / Desa', client.village || '-'], ['Alamat Domisili / Kantor', client.address || '-']] : [['Aktivitas / Kanal', log!.activity], ['Tanggal aktivitas', formatDate(log!.activityDate)], ['Petugas / PIC', db.personnel.find(p => p.id === log!.personnelId)?.name || '-'], ['Pihak dihubungi', log!.contactedParty], ['Outcome', log!.outcome], ['Next Action', log!.nextActionDate ? formatDate(log!.nextActionDate) : '-'], ['Ada pembayaran', log!.hasPayment ? receipt ? 'Ya, kuitansi sudah dicatat' : 'Ya, belum dicatat' : 'Tidak'], ['No. kuitansi', receipt?.number || '-']];
  return <Modal title={client ? client.name : log!.number} subtitle={client ? 'Master klien dan portofolio kasus terkait.' : 'Riwayat interaksi, outcome, dan tindak lanjut.'} onClose={onClose} wide={!!log} className="bounded-form-modal crm-detail-modal">
    <div className="modal-body"><div className="detail-grid">{details.map(([label, value]) => <div key={label}><span>{label}</span><div>{value}</div></div>)}</div>
      {client && <div className="crm-related-list"><div className="crm-section-heading"><h3>Portofolio kasus <span>{relatedCases.length}</span></h3><button className="text-button" onClick={() => { onClose(); openForm('cases', undefined, { clientId: client.id }); }}><Plus size={13}/>New Recovery Case</button></div>{relatedCases.length ? relatedCases.slice(0, 5).map(c => <button key={c.id} className="crm-related-row" onClick={() => openDetail('cases', c)}><BriefcaseBusiness size={15}/><span><strong>{c.number}</strong><small>{getCustomer(db, c.customerId)?.name}</small></span><span>{currency(c.principal)}</span><ArrowUpRight size={14}/></button>) : <p className="muted">Belum ada kasus yang terhubung.</p>}</div>}
      {log && <><div className="crm-report-text"><h3>Laporan Rinci Pembicaraan & Situasi Lapangan</h3><p>{log.report}</p><h3>Tindak Lanjut / Action Plan</h3><p>{log.actionPlan || 'Belum ada tindak lanjut tambahan.'}</p></div><div className="crm-detail-links"><button className="button button-secondary" onClick={() => c && openDetail('cases', c)}><BriefcaseBusiness size={15}/>{c?.number || 'Kasus'}</button><button className="button button-secondary" onClick={() => customer && openDetail('customers', customer)}><Link2 size={15}/>Data Debitur</button><button className="button button-secondary" onClick={() => { onClose(); openLetter(undefined, log.caseId); }}><FileText size={15}/>Surat Tugas</button>{log.hasPayment && (receipt || (c && canReceivePayment(db, c))) && <button className="button button-primary" onClick={() => { onClose(); if (receipt) openDetail('payments', receipt); else openForm('payments', undefined, { caseId: log.caseId, collectionLogId: log.id, date: log.activityDate }); }}><Wallet size={15}/>{receipt ? 'Lihat Pembayaran' : 'Catat Pembayaran'}</button>}{['Eksekusi Unit', 'Penarikan aset jaminan'].includes(log.activity) && c && <button className="button button-secondary" onClick={() => { const execution = db.executions.find(e => e.caseId === c.id && e.status !== 'Dibatalkan'); onClose(); if (execution) openDetail('executions', execution); else openForm('executions', undefined, { caseId: c.id, personnelId: log.personnelId, location: customer?.address || '', feeBase: c.principal }); }}><CarFront size={15}/>Kelola Tarik Unit</button>}</div></>}
    </div><footer className="modal-footer">{db.currentUser?.role !== 'Collector' ? <button className="button button-danger-ghost" onClick={() => requestDelete(entity, current)}><Trash2 size={14}/>Hapus</button> : <span/>}<button className="button button-primary" onClick={() => { onClose(); openForm(entity, current); }}><Pencil size={14}/>Edit {client ? 'Client' : 'Log'}</button></footer>
  </Modal>;
}

export function CaseConnections({ caseId }: { caseId: string }) {
  const { db, openForm, openDetail, navigate, setCollectionCaseFilter } = useArms();
  const c = getCase(db, caseId); if (!c) return null;
  const logs = [...db.collections].filter(l => l.caseId === caseId).sort((a, b) => b.activityDate.localeCompare(a.activityDate) || b.createdAt.localeCompare(a.createdAt));
  const client = db.clients.find(client => client.id === c.clientId);
  return <div className="crm-case-connections">{client && <button className="crm-client-relation" onClick={() => openDetail('clients', client)}><Building2 size={17}/><span><strong>{client.name}</strong><small>{client.code} / {client.industry} / {client.contactPerson || 'PIC belum diisi'}</small></span><ArrowUpRight size={15}/></button>}
    <div className="crm-section-heading"><h3>Collections & Communications <span>{logs.length}</span></h3><button className="text-button" onClick={() => openForm('collections', undefined, { caseId, personnelId: getAssignee(db, caseId)?.id || '' })}><Plus size={13}/>Catat aktivitas</button></div>
    {logs.length ? logs.slice(0, 3).map(log => <button className="crm-history-row" key={log.id} onClick={() => openDetail('collections', log)}><MessageSquareText size={15}/><span><strong>{log.activity}</strong><small>{log.outcome}</small></span><time>{formatDate(log.activityDate)}</time></button>) : <p className="form-note">Belum ada riwayat komunikasi untuk kasus ini.</p>}
    {logs.length > 0 && <button className="text-button" onClick={() => { setCollectionCaseFilter(caseId); navigate('collections'); }}><CalendarCheck2 size={14}/>Lihat seluruh log & tindak lanjut<ArrowUpRight size={14}/></button>}
  </div>;
}