import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { AlertCircle, ArrowDownLeft, ArrowDownToLine, ArrowUpRight, Building2, Calculator, CheckCircle2, MoreHorizontal, Pencil, Plus, Save, Search, ShieldCheck, Trash2, Wallet } from 'lucide-react';
import { useArms } from '../lib/context';
import { accountBalance, calculatePayment, canReceivePayment, currency, exportCsv, feeSources, formatDate, getAssignee, getCase, getCustomer, isCaseSuccessful, isoToday, postedFee, type AccountTransaction, type BankAccount, type Execution, type RecordData } from '../lib/data';
import { EmptyState, Field, Modal, Pagination, Select, Spinner, StatusBadge } from './ui';

export type FinanceEntity = 'executions' | 'accounts' | 'transactions';
const sourceOptions = [{ value: 'multifinance', label: 'Fee dari Client / Creditor' }, { value: 'payment', label: 'Fee dari pembayaran debitur' }, { value: 'execution', label: 'Fee dari tarik unit selesai' }, { value: 'case', label: 'Fee tambahan kasus selesai' }, { value: 'manual', label: 'Pencatatan manual / operasional' }];
const executionStatuses = ['Dijadwalkan', 'Dalam Proses', 'Selesai', 'Dibatalkan'];
const labels = { executions: 'Tarik Unit', accounts: 'Rekening', transactions: 'Transaksi Rekening' };

export function FinanceForm({ entity, record, defaults, busy, error, onClose, onSubmit }: { entity: FinanceEntity; record?: RecordData; defaults?: Record<string, unknown>; busy: boolean; error: string; onClose: () => void; onSubmit: (data: Partial<RecordData>) => void }) {
  const { db } = useArms();
  const initial: Record<string, string | number> = entity === 'executions' ? { caseId: '', personnelId: '', date: isoToday(), location: '', method: 'Penyerahan Sukarela', authorityRef: '', handoverRef: '', status: 'Dijadwalkan', feeBase: 0, feeRate: 10, partnerRate: db.settings.partnerRate, notes: '' } : entity === 'accounts' ? { name: '', bank: '', number: '', holder: db.settings.agency, openingBalance: 0 } : { accountId: db.accounts[0]?.id || '', date: isoToday(), type: 'Pemasukan', category: 'Fee Klien', sourceType: 'multifinance', sourceId: '', caseId: '', client: '', amount: 0, reference: '', description: '' };
  const [values, setValues] = useState<Record<string, string | number>>({ ...initial, ...(record as unknown as Record<string, string | number>), ...(defaults as Record<string, string | number>) } as Record<string, string | number>);
  const text = (key: string) => String(values[key] ?? '');
  const num = (key: string) => Number(values[key] || 0);
  const set = (key: string, value: string | number) => setValues(v => ({ ...v, [key]: value }));
  const input = (key: string, type = 'text', required = true, max?: number) => <input name={key} type={type} value={text(key)} onChange={e => set(key, e.target.value)} required={required} min={type === 'number' ? 0 : undefined} max={max} step={type === 'number' && max === 100 ? '0.01' : undefined}/>;
  const select = (key: string, options: string[]) => <select value={text(key)} onChange={e => set(key, e.target.value)}>{options.map(o => <option key={o}>{o}</option>)}</select>;
  const totals = calculatePayment(num('feeBase'), num('feeRate'), num('partnerRate'), []);
  const sources = feeSources(db);
  const source = sources.find(s => s.type === text('sourceType') && s.id === text('sourceId'));
  const sourceRemaining = source ? Math.max(0, (text('type') === 'Pemasukan' ? source.amount : source.partner) - postedFee(db, source.type, source.id, text('type') as AccountTransaction['type'], record?.id)) : undefined;
  function selectSource(id: string) {
    const selected = sources.find(s => s.type === text('sourceType') && s.id === id);
    const c = getCase(db, selected?.caseId || id);
    const remaining = selected ? Math.max(0, (text('type') === 'Pemasukan' ? selected.amount : selected.partner) - postedFee(db, selected.type, selected.id, text('type') as AccountTransaction['type'], record?.id)) : 0;
    setValues(v => ({ ...v, sourceId: id, caseId: c?.id || '', client: c?.client || '', clientId: c?.clientId || '', amount: remaining, description: `${text('type') === 'Pengeluaran' ? 'Komisi mitra' : 'Penerimaan fee'} ${selected?.number || c?.number || ''}` }));
  }
  function submit(event: FormEvent) {
    event.preventDefault(); if (busy) return;
    const data = { ...values };
    ['feeBase', 'feeRate', 'partnerRate', 'amount', 'openingBalance'].forEach(key => { if (key in data) data[key] = num(key); });
    if (entity === 'executions') Object.assign(data, totals);
    onSubmit(data as unknown as Partial<RecordData>);
  }
  return <Modal title={`${record ? 'Edit' : entity === 'transactions' ? 'Catat' : 'Tambah'} ${labels[entity]}`} subtitle={entity === 'executions' ? 'Kelola penugasan, serah terima unit, dan pembagian fee.' : entity === 'accounts' ? 'Daftarkan rekening bank atau kas operasional agensi.' : 'Catat uang fee yang benar-benar masuk atau keluar.'} onClose={onClose} wide={entity === 'executions'} className="bounded-form-modal">
    <form onSubmit={submit}><fieldset disabled={busy} className="form-fieldset"><div className="modal-body">
      {entity === 'executions' && <><div className="form-grid">
        <Field label="Kasus / debitur" required className="span-2"><select value={text('caseId')} required onChange={e => { const c = getCase(db, e.target.value); const customer = getCustomer(db, c?.customerId || ''); setValues(v => ({ ...v, caseId: c?.id || '', feeBase: c?.principal || 0, location: customer?.address || '', personnelId: c ? getAssignee(db, c.id)?.id || '' : '' })); }}><option value="">Pilih kasus aktif</option>{db.cases.filter(c => c.id === (record as Execution)?.caseId || (canReceivePayment(db, c) && !db.executions.some(e => e.caseId === c.id && e.status !== 'Dibatalkan'))).map(c => <option key={c.id} value={c.id}>{c.number} - {getCustomer(db, c.customerId)?.name}</option>)}</select></Field>
        <Field label="Tanggal pelaksanaan" required>{input('date', 'date')}</Field><Field label="Petugas" required><select required value={text('personnelId')} onChange={e => set('personnelId', e.target.value)}><option value="">Pilih petugas</option>{db.personnel.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>
        <Field label="Metode penarikan">{select('method', ['Penyerahan Sukarela', 'Eksekusi Sesuai Dokumen'])}</Field><Field label="Status pelaksanaan">{select('status', executionStatuses)}</Field>
        <Field label="Lokasi / alamat unit" required className="span-2">{input('location')}</Field><Field label="Referensi kuasa / dokumen sah" required>{input('authorityRef')}</Field><Field label="Nomor BAST / serah terima" required={text('status') === 'Selesai'}>{input('handoverRef', 'text', text('status') === 'Selesai')}</Field>
      </div><div className="form-section-label"><Calculator size={15}/>Perhitungan fee penarikan</div><div className="form-grid finance-three"><Field label="Dasar fee (Rp)" required hint="Nilai yang disepakati dengan klien.">{input('feeBase', 'number')}</Field><Field label="Persentase fee (%)" required>{input('feeRate', 'number', true, 100)}</Field><Field label="Hak mitra (%)" required>{input('partnerRate', 'number', true, 100)}</Field></div>
      <div className="fee-calculation-inline"><div><span>Gross fee</span><strong>{currency(totals.grossFee)}</strong></div><div><span>Hak perusahaan</span><strong className="emerald-text">{currency(totals.companyRevenue)}</strong></div><div><span>Hak mitra</span><strong>{currency(totals.partnerCommission)}</strong></div></div>
      <Field label="Catatan"><textarea rows={2} value={text('notes')} onChange={e => set('notes', e.target.value)}/></Field><p className="form-note"><ShieldCheck size={14}/>Penarikan hanya dengan persetujuan dan dokumen yang sah. Unit selesai ditarik tidak otomatis melunasi piutang atau menambah saldo rekening.</p></>}
      {entity === 'accounts' && <div className="form-grid"><Field label="Nama rekening" required className="span-2">{input('name')}</Field><Field label="Bank / jenis kas" required>{input('bank')}</Field><Field label="Nomor rekening / kode kas" required>{input('number')}</Field><Field label="Atas nama" required className="span-2">{input('holder')}</Field><Field label="Saldo awal (Rp)" required className="span-2">{input('openingBalance', 'number')}</Field></div>}
      {entity === 'transactions' && <><div className="transaction-direction">{(['Pemasukan', 'Pengeluaran'] as const).map(type => <button type="button" key={type} className={text('type') === type ? `active ${type === 'Pemasukan' ? 'income' : 'expense'}` : ''} onClick={() => setValues(v => ({ ...v, type, sourceId: '', amount: 0, category: type === 'Pemasukan' ? 'Fee Klien' : 'Operasional' }))}>{type === 'Pemasukan' ? <ArrowDownLeft size={16}/> : <ArrowUpRight size={16}/>} {type}</button>)}</div>
      {!db.accounts.length && <div className="form-error"><AlertCircle size={15}/>Tambahkan rekening dari menu Rekening terlebih dahulu.</div>}
      <div className="form-grid"><Field label="Rekening" required><select required value={text('accountId')} onChange={e => set('accountId', e.target.value)}><option value="">Pilih rekening</option>{db.accounts.map(a => <option key={a.id} value={a.id}>{a.name} / {a.bank}</option>)}</select></Field><Field label="Tanggal transaksi" required>{input('date', 'date')}</Field>
        <Field label="Sumber transaksi" className="span-2"><select value={text('sourceType')} onChange={e => setValues(v => ({ ...v, sourceType: e.target.value, sourceId: '', caseId: '', clientId: '', client: '', amount: 0 }))}>{sourceOptions.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select></Field>
        {['payment', 'execution', 'case'].includes(text('sourceType')) ? <Field label="Referensi kasus / fee" required className="span-2"><select required value={text('sourceId')} onChange={e => selectSource(e.target.value)}><option value="">Pilih sumber fee</option>{text('sourceType') === 'case' ? db.cases.filter(c => isCaseSuccessful(db, c)).map(c => <option key={c.id} value={c.id}>{c.number} / {c.client} / {getCustomer(db, c.customerId)?.name}</option>) : sources.filter(s => s.type === text('sourceType') && (s.id === text('sourceId') || (text('type') === 'Pemasukan' ? s.remaining : s.partner - postedFee(db, s.type, s.id, 'Pengeluaran')) > 0)).map(s => <option key={s.id} value={s.id}>{s.number} / {getCustomer(db, getCase(db, s.caseId)?.customerId || '')?.name}</option>)}</select></Field> : text('sourceType') === 'multifinance' ? <Field label="Client / Creditor" required className="span-2"><select required value={text('clientId')} onChange={e => { const client = db.clients.find(c => c.id === e.target.value); setValues(v => ({ ...v, clientId: client?.id || '', client: client?.name || '' })); }}><option value="">Pilih dari master klien</option>{db.clients.map(c => <option key={c.id} value={c.id}>{c.code} / {c.name} / {c.industry}</option>)}</select></Field> : <Field label="Pihak terkait" className="span-2">{input('client', 'text', false)}</Field>}
        {sourceRemaining !== undefined && <div className="payment-case-info span-2"><span>{text('type') === 'Pemasukan' ? 'Sisa fee belum diterima' : 'Sisa komisi belum dibayarkan'}</span><strong>{currency(sourceRemaining)}</strong></div>}
        <Field label="Nominal aktual (Rp)" required><input type="number" min="1" max={sourceRemaining} value={text('amount')} onChange={e => set('amount', e.target.value)} required/></Field>
        <Field label="Kategori">{['payment', 'execution'].includes(text('sourceType')) ? <input value={text('type') === 'Pengeluaran' ? 'Komisi Mitra' : text('sourceType') === 'execution' ? 'Fee Tarik Unit' : 'Fee Penagihan'} readOnly/> : select('category', text('type') === 'Pemasukan' ? ['Fee Klien', 'Fee Penagihan', 'Fee Tarik Unit', 'Fee Kasus Selesai', 'Lainnya'] : ['Operasional', 'Komisi Mitra', 'Administrasi', 'Transportasi', 'Lainnya'])}</Field>
        <Field label="No. referensi / bukti transfer" required className="span-2">{input('reference')}</Field><Field label="Keterangan" required className="span-2"><textarea required rows={2} value={text('description')} onChange={e => set('description', e.target.value)}/></Field>
      </div><p className="form-note"><Wallet size={14}/>Hanya nominal yang disimpan di sini yang mengubah saldo rekening. Pembayaran pokok debitur tidak otomatis menjadi pemasukan fee.</p></>}
      {error && <div className="form-error" role="alert"><AlertCircle size={15}/>{error}</div>}
    </div><footer className="modal-footer"><button type="button" className="button button-secondary" onClick={onClose}>Batal</button><button type="submit" className="button button-primary" disabled={busy || (entity === 'transactions' && !db.accounts.length)}>{busy ? <Spinner/> : <Save size={15}/>} {busy ? 'Menyimpan...' : `Simpan ${labels[entity]}`}</button></footer></fieldset></form>
  </Modal>;
}

export function ExecutionsModule() {
  const { db, openDetail, openForm, notify } = useArms();
  const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1);
  const rows = db.executions.filter(e => (!status || e.status === status) && `${e.number} ${getCase(db, e.caseId)?.number} ${getCustomer(db, getCase(db, e.caseId)?.customerId || '')?.name} ${e.location}`.toLowerCase().includes(query.toLowerCase()));
  useEffect(() => setPage(1), [query, status, db.executions.length]);
  useEffect(() => setPage(current => Math.min(current, Math.max(1, Math.ceil(rows.length / 10)))), [rows.length]);
  return <div className="module-stack"><div className="report-stats">{[{ label: 'Penugasan berjalan', value: db.executions.filter(e => ['Dijadwalkan', 'Dalam Proses'].includes(e.status)).length + ' unit' }, { label: 'Unit selesai ditarik', value: db.executions.filter(e => e.status === 'Selesai').length + ' unit' }, { label: 'Fee penarikan selesai', value: currency(db.executions.filter(e => e.status === 'Selesai').reduce((sum, e) => sum + e.grossFee, 0)) }].map(s => <div className="report-stat" key={s.label}><span>{s.label}</span><strong>{s.value}</strong></div>)}</div>
    <section className="panel"><div className="entity-toolbar"><div className="table-search"><Search size={15}/><input aria-label="Cari penarikan unit" placeholder="Cari unit atau debitur..." value={query} onChange={e => setQuery(e.target.value)}/></div><div className="entity-toolbar-right"><Select label="Status tarik unit" value={status} onChange={setStatus} options={[{ value: '', label: 'Semua status' }, ...executionStatuses.map(s => ({ value: s, label: s }))]}/><button className="button button-secondary button-small" onClick={() => { exportCsv('ARMS-tarik-unit.csv', [['No Penarikan', 'Kasus', 'Debitur', 'Tanggal', 'Status', 'Dasar Fee', 'Fee (%)', 'Gross Fee', 'Perusahaan', 'Mitra', 'Dokumen', 'BAST'], ...rows.map(e => [e.number, getCase(db, e.caseId)?.number || '', getCustomer(db, getCase(db, e.caseId)?.customerId || '')?.name || '', e.date, e.status, e.feeBase, e.feeRate, e.grossFee, e.companyRevenue, e.partnerCommission, e.authorityRef, e.handoverRef])]); notify('Data penarikan diekspor.'); }}><ArrowDownToLine size={14}/>Ekspor</button></div></div>
    <div className="table-overflow"><table className="data-table"><thead><tr><th>Penarikan / Debitur</th><th>Unit / Klien</th><th>Tanggal / Petugas</th><th>Fee</th><th>Hak perusahaan</th><th>Status</th><th/></tr></thead><tbody>{rows.slice((page - 1) * 10, page * 10).map(e => { const c = getCase(db, e.caseId), customer = getCustomer(db, c?.customerId || ''); return <tr key={e.id}><td><button className="case-link" onClick={() => openDetail('executions', e)}>{e.number}</button><div className="cell-secondary">{customer?.name}</div></td><td>{customer?.brandType || c?.asset || '-'}<div className="cell-secondary">{customer?.plate || c?.client}</div></td><td>{formatDate(e.date)}<div className="cell-secondary">{db.personnel.find(p => p.id === e.personnelId)?.name}</div></td><td className="money-cell">{currency(e.grossFee)}<div className="cell-secondary">{e.feeRate}% x {currency(e.feeBase)}</div></td><td className="emerald-text">{currency(e.companyRevenue)}</td><td><StatusBadge status={e.status}/></td><td><button className="icon-button" onClick={() => openDetail('executions', e)} aria-label={`Kelola ${e.number}`}><MoreHorizontal size={17}/></button></td></tr>; })}</tbody></table></div>
    {!rows.length && <EmptyState title="Belum ada penarikan unit" description="Buat penugasan dengan dokumen kuasa yang sah." action={<button className="button button-primary" onClick={() => openForm('executions')}><Plus size={14}/>Tambah penarikan</button>}/>}<Pagination page={page} setPage={setPage} total={rows.length}/></section><p className="report-note"><ShieldCheck size={15}/>Fee di atas adalah hak dari penugasan. Catat penerimaan aktualnya di Rekening setelah dana diterima.</p>
  </div>;
}

export function AccountsModule() {
  const { db, openForm, openDetail, notify } = useArms();
  const [tab, setTab] = useState('transactions'); const [accountId, setAccountId] = useState(''); const [query, setQuery] = useState(''); const [type, setType] = useState(''); const [month, setMonth] = useState(''); const [page, setPage] = useState(1);
  const canWrite = db.currentUser?.role !== 'Collector';
  useEffect(() => setPage(1), [tab, accountId, query, type, month, db.transactions.length]);
  const transactions = useMemo(() => [...db.transactions].filter(t => (!accountId || t.accountId === accountId) && (!type || t.type === type) && (!month || t.date.startsWith(month)) && `${t.number} ${t.client} ${t.description} ${t.reference}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.date.localeCompare(a.date)), [db.transactions, accountId, type, month, query]);
  const sources = feeSources(db).filter(s => s.remaining > 0 && `${s.number} ${getCase(db, s.caseId)?.client} ${getCustomer(db, getCase(db, s.caseId)?.customerId || '')?.name}`.toLowerCase().includes(query.toLowerCase()));
  const rowCount = tab === 'fees' ? sources.length : transactions.length;
  useEffect(() => setPage(current => Math.min(current, Math.max(1, Math.ceil(rowCount / 10)))), [rowCount]);
  useEffect(() => { if (accountId && !db.accounts.some(a => a.id === accountId)) setAccountId(''); }, [db.accounts, accountId]);
  const income = transactions.filter(t => t.type === 'Pemasukan').reduce((sum, t) => sum + t.amount, 0), expense = transactions.filter(t => t.type === 'Pengeluaran').reduce((sum, t) => sum + t.amount, 0);
  const balance = db.accounts.filter(a => !accountId || a.id === accountId).reduce((sum, a) => sum + accountBalance(db, a.id), 0);
  return <div className="module-stack"><div className="report-stats"><div className="report-stat"><span>Saldo rekening saat ini</span><strong>{currency(balance)}</strong><small>Saldo awal + seluruh mutasi</small></div><div className="report-stat"><span>Pemasukan fee</span><strong className="emerald-text">{currency(income)}</strong><small>Sesuai filter mutasi</small></div><div className="report-stat"><span>Pengeluaran</span><strong>{currency(expense)}</strong><small>Sesuai filter mutasi</small></div></div>
    <section className="panel"><div className="account-module-tabs"><div className="table-tabs">{[{ id: 'transactions', label: 'Mutasi rekening' }, { id: 'accounts', label: 'Daftar rekening' }, { id: 'fees', label: 'Fee belum dicatat' }].map(t => <button key={t.id} className={tab === t.id ? 'active' : ''} onClick={() => setTab(t.id)}>{t.label}</button>)}</div>{canWrite && <button className="text-button" onClick={() => openForm('accounts')}><Plus size={14}/>Tambah rekening</button>}</div>
      {tab !== 'accounts' && <div className="entity-toolbar"><div className="table-search"><Search size={15}/><input aria-label="Cari mutasi atau fee" placeholder="Cari klien, kasus, referensi..." value={query} onChange={e => setQuery(e.target.value)}/></div><div className="entity-toolbar-right">{tab === 'transactions' && <><Select label="Filter rekening" value={accountId} onChange={setAccountId} options={[{ value: '', label: 'Semua rekening' }, ...db.accounts.map(a => ({ value: a.id, label: a.name }))]}/><Select label="Jenis mutasi" value={type} onChange={setType} options={[{ value: '', label: 'Semua mutasi' }, { value: 'Pemasukan', label: 'Pemasukan' }, { value: 'Pengeluaran', label: 'Pengeluaran' }]}/><input className="month-filter" type="month" aria-label="Bulan mutasi" value={month} onChange={e => setMonth(e.target.value)}/><button className="button button-small button-secondary" aria-label="Ekspor mutasi" onClick={() => { exportCsv('ARMS-mutasi-rekening.csv', [['Nomor', 'Tanggal', 'Rekening', 'Jenis', 'Kategori', 'Klien', 'Nominal', 'Referensi', 'Keterangan'], ...transactions.map(t => [t.number, t.date, db.accounts.find(a => a.id === t.accountId)?.name || '', t.type, t.category, t.client, t.amount, t.reference, t.description])]); notify('Mutasi rekening diekspor.'); }}><ArrowDownToLine size={14}/></button></>}</div></div>}
      <div className="table-overflow"><table className="data-table"><thead><tr>{tab === 'transactions' ? <><th>Transaksi / Tanggal</th><th>Rekening</th><th>Keterangan / Klien</th><th>Jenis</th><th>Nominal</th><th>Referensi</th></> : tab === 'accounts' ? <><th>Nama rekening</th><th>Bank</th><th>Nomor rekening</th><th>Atas nama</th><th>Saldo</th></> : <><th>Sumber fee</th><th>Kasus / Debitur</th><th>Hak fee</th><th>Sudah diterima</th><th>Belum dicatat</th></>}<th/></tr></thead><tbody>
      {tab === 'transactions' && transactions.slice((page - 1) * 10, page * 10).map(t => <tr key={t.id}><td><button className="case-link" onClick={() => openDetail('transactions', t)}>{t.number}</button><div className="cell-secondary">{formatDate(t.date)}</div></td><td>{db.accounts.find(a => a.id === t.accountId)?.name}</td><td>{t.description}<div className="cell-secondary">{t.client || t.category}</div></td><td><span className={`money-direction ${t.type === 'Pemasukan' ? 'in' : 'out'}`}>{t.type === 'Pemasukan' ? <ArrowDownLeft size={13}/> : <ArrowUpRight size={13}/>} {t.type}</span></td><td className={t.type === 'Pemasukan' ? 'emerald-text' : 'money-cell'}>{t.type === 'Pemasukan' ? '+' : '-'}{currency(t.amount)}</td><td>{t.reference}</td><td><button className="icon-button" onClick={() => openDetail('transactions', t)} aria-label={`Detail ${t.number}`}><MoreHorizontal size={16}/></button></td></tr>)}
      {tab === 'accounts' && db.accounts.map(a => <tr key={a.id}><td><button className="name-cell" onClick={() => openDetail('accounts', a)}><span className="document-icon"><Building2 size={16}/></span><strong>{a.name}</strong></button></td><td>{a.bank}</td><td>{a.number}</td><td>{a.holder}</td><td className="money-cell">{currency(accountBalance(db, a.id))}</td><td><button className="icon-button" onClick={() => openDetail('accounts', a)} aria-label={`Kelola ${a.name}`}><MoreHorizontal size={16}/></button></td></tr>)}
      {tab === 'fees' && sources.slice((page - 1) * 10, page * 10).map(s => <tr key={`${s.type}-${s.id}`}><td>{s.number}<div className="cell-secondary">{s.type === 'execution' ? 'Tarik unit selesai' : 'Fee pembayaran'}</div></td><td>{getCase(db, s.caseId)?.number}<div className="cell-secondary">{getCustomer(db, getCase(db, s.caseId)?.customerId || '')?.name}</div></td><td>{currency(s.amount)}</td><td>{currency(s.recorded)}</td><td className="emerald-text">{currency(s.remaining)}</td><td>{canWrite && <button className="button button-small button-secondary" onClick={() => openForm('transactions', undefined, { sourceType: s.type, sourceId: s.id, amount: s.remaining, caseId: s.caseId, client: getCase(db, s.caseId)?.client || '', description: `Penerimaan fee ${s.number}` })}><Plus size={13}/>Catat masuk</button>}</td></tr>)}
      </tbody></table></div>
      {(tab === 'transactions' ? !transactions.length : tab === 'accounts' ? !db.accounts.length : !sources.length) && <EmptyState title={tab === 'fees' ? 'Tidak ada fee tertunda' : tab === 'accounts' ? 'Belum ada rekening' : 'Belum ada mutasi'} description={tab === 'fees' ? 'Seluruh fee sumber yang tersedia sudah dicatat.' : 'Tambahkan rekening dan catat pemasukan atau pengeluaran aktual.'} action={canWrite && <button className="button button-primary" onClick={() => openForm(!db.accounts.length ? 'accounts' : 'transactions')}><Plus size={14}/>{!db.accounts.length ? 'Tambah rekening' : 'Catat transaksi'}</button>}/>}
      {tab !== 'accounts' && <Pagination page={page} setPage={setPage} total={tab === 'fees' ? sources.length : transactions.length}/>}
    </section><p className="report-note"><CheckCircle2 size={15}/>Buku kas fee terpisah dari pokok piutang. Satu sumber fee dapat dicatat bertahap, tanpa melebihi hak fee yang dihitung.</p>
  </div>;
}

export function FinanceDetail({ entity, record, onClose }: { entity: FinanceEntity; record: RecordData; onClose: () => void }) {
  const { db, openForm, requestDelete } = useArms();
  const current = (db[entity] as RecordData[]).find(r => r.id === record.id) || record;
  const canWrite = db.currentUser?.role !== 'Collector' || entity === 'executions';
  let title = '', details: [string, string][] = [];
  if (entity === 'executions') { const e = current as Execution, c = getCase(db, e.caseId); title = e.number; details = [['Kasus', c?.number || '-'], ['Debitur', getCustomer(db, c?.customerId || '')?.name || '-'], ['Petugas', db.personnel.find(p => p.id === e.personnelId)?.name || '-'], ['Tanggal', formatDate(e.date)], ['Metode', e.method], ['Status', e.status], ['Lokasi', e.location], ['Dokumen kuasa', e.authorityRef], ['BAST', e.handoverRef || '-'], ['Dasar fee', currency(e.feeBase)], ['Persentase fee', `${e.feeRate}%`], ['Gross fee', currency(e.grossFee)], ['Hak perusahaan', currency(e.companyRevenue)], ['Hak mitra', currency(e.partnerCommission)], ['Catatan', e.notes || '-']]; }
  if (entity === 'accounts') { const a = current as BankAccount; title = a.name; details = [['Bank', a.bank], ['Nomor rekening', a.number], ['Atas nama', a.holder], ['Saldo awal', currency(a.openingBalance)], ['Saldo saat ini', currency(accountBalance(db, a.id))]]; }
  if (entity === 'transactions') { const t = current as AccountTransaction; title = t.number; details = [['Rekening', db.accounts.find(a => a.id === t.accountId)?.name || '-'], ['Tanggal', formatDate(t.date)], ['Jenis', t.type], ['Kategori', t.category], ['Nominal', currency(t.amount)], ['Klien / pihak terkait', t.client || '-'], ['Referensi', t.reference], ['Keterangan', t.description], ['Sumber', sourceOptions.find(o => o.value === t.sourceType)?.label || t.sourceType], ['Kasus', getCase(db, t.caseId)?.number || '-']]; }
  return <Modal title={title} subtitle={`Detail ${labels[entity].toLowerCase()}.`} onClose={onClose}><div className="modal-body"><div className="detail-grid">{details.map(([label, value]) => <div key={label}><span>{label}</span><div>{value}</div></div>)}</div>{entity === 'executions' && (current as Execution).status === 'Selesai' && db.currentUser?.role !== 'Collector' && <div className="detail-quick-actions"><button className="button button-secondary" onClick={() => { onClose(); const e = current as Execution; openForm('transactions', undefined, { sourceType: 'execution', sourceId: e.id, amount: Math.max(0, e.grossFee - postedFee(db, 'execution', e.id, 'Pemasukan')), description: `Penerimaan fee ${e.number}` }); }}><Wallet size={15}/>Catat penerimaan fee</button></div>}</div><footer className="modal-footer">{db.currentUser?.role !== 'Collector' ? <button className="button button-danger-ghost" onClick={() => requestDelete(entity, current)}><Trash2 size={14}/>Hapus</button> : <span/>}{canWrite && <button className="button button-primary" onClick={() => { onClose(); openForm(entity, current); }}><Pencil size={14}/>Edit data</button>}</footer></Modal>;
}